// Cart recovery state — single source of truth for the croko_cart_state
// localStorage envelope. Mirrored by the Frappe Abandoned Cart system: the
// `cart_uuid` here is what the recovery emails put in the `?cart=` query
// param, and what the Frappe webhook stores on the Abandoned Cart record.
//
// Shape (v1):
// {
//   cart_uuid: string,        // CROKO-<ts>-<rand>, generated by usePurchaseModal
//   step: number,             // 1..TOTAL_STEPS — last step the buyer reached
//   data: {
//     gender: 'boy' | 'girl' | null,
//     selectedImages: string[],
//     babyName: string,
//     email: string
//   },
//   updated_at: ISO string,
//   expires_at: ISO string    // 90 days after last update
// }

export const CART_STATE_KEY = 'croko_cart_state';
const TTL_DAYS = 90;
const TTL_MS = TTL_DAYS * 24 * 60 * 60 * 1000;

const isBrowser = () => typeof window !== 'undefined' && !!window.localStorage;

const emptyData = () => ({
  gender: null,
  selectedImages: [],
  babyName: '',
  email: ''
});

const isShapeValid = (parsed) =>
  parsed &&
  typeof parsed === 'object' &&
  typeof parsed.cart_uuid === 'string' &&
  parsed.cart_uuid.length > 0 &&
  parsed.data &&
  typeof parsed.data === 'object';

export const readCartState = () => {
  if (!isBrowser()) return null;
  try {
    const raw = window.localStorage.getItem(CART_STATE_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw);
    if (!isShapeValid(parsed)) {
      window.localStorage.removeItem(CART_STATE_KEY);
      return null;
    }
    if (parsed.expires_at && Date.parse(parsed.expires_at) < Date.now()) {
      window.localStorage.removeItem(CART_STATE_KEY);
      return null;
    }
    return parsed;
  } catch (e) {
    console.warn('[cartState] failed to read, clearing:', e);
    try { window.localStorage.removeItem(CART_STATE_KEY); } catch (_) {}
    return null;
  }
};

export const writeCartState = ({ cartUuid, step, data }) => {
  if (!isBrowser() || !cartUuid) return;
  try {
    const now = Date.now();
    const envelope = {
      cart_uuid: cartUuid,
      step: typeof step === 'number' ? step : 1,
      data: { ...emptyData(), ...(data || {}) },
      updated_at: new Date(now).toISOString(),
      expires_at: new Date(now + TTL_MS).toISOString()
    };
    window.localStorage.setItem(CART_STATE_KEY, JSON.stringify(envelope));
  } catch (e) {
    console.warn('[cartState] failed to write:', e);
  }
};

export const clearCartState = () => {
  if (!isBrowser()) return;
  try { window.localStorage.removeItem(CART_STATE_KEY); } catch (_) {}
};

// Flat shape used by useWhatsAppRedirect / useOrderTracking — they only care
// about the inner `data` plus a couple of legacy field names.
export const getFlatSelections = () => {
  const state = readCartState();
  if (!state) return null;
  return {
    ...state.data,
    cart_uuid: state.cart_uuid,
    timestamp: Date.parse(state.updated_at) || Date.now()
  };
};
